//! Recognizing a Claude Code local slash command inside a `user` record's plain-text content.
//!
//! The invocation (`<command-name>…</command-name>` plus an optional `<command-args>`) and its
//! `<local-command-stdout>` result. Tag order is not fixed — a built-in command writes
//! `command-name` first, a custom or project command writes `command-message` first — so this
//! looks each tag up by name rather than assuming a position.

const NAME_TAG: &str = "command-name";
const ARGS_TAG: &str = "command-args";
const STDOUT_TAG: &str = "local-command-stdout";

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Command<'a> {
    Invocation { name: &'a str, args: Option<&'a str> },
    Output(&'a str),
}

pub fn parse(text: &str) -> Option<Command<'_>> {
    if let Some(output) = tag(text, STDOUT_TAG) {
        return Some(Command::Output(output.trim()));
    }
    let name = tag(text, NAME_TAG)?.trim();
    let args = tag(text, ARGS_TAG).map(str::trim).filter(|args| !args.is_empty());
    Some(Command::Invocation { name, args })
}

fn tag<'a>(text: &'a str, name: &str) -> Option<&'a str> {
    let open = format!("<{name}>");
    let close = format!("</{name}>");
    let after = text.find(&open).and_then(|at| at.checked_add(open.len()))?;
    let rest = text.get(after..)?;
    let end = rest.find(&close)?;
    rest.get(..end)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_built_in_command_writes_the_name_tag_first_and_carries_no_args() {
        let text = "<command-name>/theme</command-name>\n            <command-message>theme</command-message>\n            <command-args></command-args>";
        assert_eq!(parse(text), Some(Command::Invocation { name: "/theme", args: None }));
    }

    #[test]
    fn a_custom_command_writes_the_message_tag_first_and_the_args_hold_the_real_prompt() {
        let text = "<command-message>opsx:explore</command-message>\n<command-name>/opsx:explore</command-name>\n<command-args>the third view is hard to read</command-args>";
        assert_eq!(
            parse(text),
            Some(Command::Invocation { name: "/opsx:explore", args: Some("the third view is hard to read") })
        );
    }

    #[test]
    fn a_command_with_no_message_tag_at_all_still_parses_by_name() {
        assert_eq!(parse("<command-name>/exit</command-name>"), Some(Command::Invocation { name: "/exit", args: None }));
    }

    #[test]
    fn whitespace_only_args_read_as_no_args() {
        let text = "<command-name>/plan</command-name><command-args>   \n  </command-args>";
        assert_eq!(parse(text), Some(Command::Invocation { name: "/plan", args: None }));
    }

    #[test]
    fn a_stdout_result_is_the_output_shape_trimmed() {
        assert_eq!(
            parse("<local-command-stdout>Using custom theme \"Default+\"</local-command-stdout>"),
            Some(Command::Output("Using custom theme \"Default+\""))
        );
    }

    #[test]
    fn a_multi_line_stdout_result_survives_whole() {
        let text = "<local-command-stdout>Current Plan\n/home/oc/.claude/plans/x.md\n\n# Title</local-command-stdout>";
        assert_eq!(parse(text), Some(Command::Output("Current Plan\n/home/oc/.claude/plans/x.md\n\n# Title")));
    }

    #[test]
    fn the_caveat_wrapper_matches_neither_shape() {
        let text = "<local-command-caveat>Caveat: the messages below were generated by the user while running local commands.</local-command-caveat>";
        assert_eq!(parse(text), None);
    }

    #[test]
    fn ordinary_prose_is_not_a_command() {
        assert_eq!(parse("read the grid scanner back to me"), None);
        assert_eq!(parse(""), None);
    }

    #[test]
    fn a_stdout_tag_wins_over_a_stray_command_name_tag_in_the_same_text() {
        let text = "<command-name>/theme</command-name><local-command-stdout>ok</local-command-stdout>";
        assert_eq!(parse(text), Some(Command::Output("ok")));
    }
}
