//! Turning a raw prompt into the single line a session list can carry as a title.
//!
//! A `user` record's content is the prompt Claude Code assembled, not the words that were
//! typed: a local slash command arrives as its `<command-name>` envelope, a paste as a
//! `<pasted_content>` block, and the harness adds `<system-reminder>` and
//! `<local-command-caveat>` wrappers around text the user never wrote. Only those known
//! envelopes are removed — a prompt that genuinely talks about `<div>` keeps it.

use crate::domain::command::{self, Command};
use crate::domain::paste;
use crate::domain::text;

const ENVELOPES: [&str; 3] = ["system-reminder", "local-command-caveat", "local-command-stdout"];

pub fn from_prompt(raw: &str) -> Option<String> {
    let mut text = text::unescape(raw);
    for name in ENVELOPES {
        text = without(&text, name);
    }
    if let Some(Command::Invocation { name, args }) = command::parse(&text) {
        let invocation = args.map_or_else(|| name.to_owned(), |args| format!("{name} {args}"));
        return one_line(&invocation);
    }
    one_line(&paste::unwrapped(&text))
}

pub fn from_latch(raw: &str) -> Option<String> {
    one_line(&text::unescape(raw))
}

fn without(text: &str, name: &str) -> String {
    let open = format!("<{name}");
    let close = format!("</{name}>");
    let mut out = String::with_capacity(text.len());
    let mut rest = text;
    while let Some(at) = rest.find(&open) {
        let Some(body) = rest.get(at..) else { break };
        let Some(end) = body.find(&close).and_then(|end| end.checked_add(close.len())) else { break };
        out.push_str(rest.get(..at).unwrap_or_default());
        rest = body.get(end..).unwrap_or_default();
    }
    out.push_str(rest);
    out
}

fn one_line(text: &str) -> Option<String> {
    let mut out = String::with_capacity(text.len());
    for word in text.split_whitespace() {
        if !out.is_empty() {
            out.push(' ');
        }
        out.push_str(word);
    }
    if out.is_empty() { None } else { Some(out) }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_slash_command_prompt_reads_as_the_command_it_invoked() {
        let raw = r"<command-name>/clear</command-name>\n            <command-message>clear</command-message>\n            <command-args></command-args>";
        assert_eq!(from_prompt(raw).as_deref(), Some("/clear"));
    }

    #[test]
    fn a_custom_command_keeps_its_arguments() {
        let raw = r"<command-message>explore</command-message>\n<command-name>/explore</command-name>\n<command-args>the grid scanner</command-args>";
        assert_eq!(from_prompt(raw).as_deref(), Some("/explore the grid scanner"));
    }

    #[test]
    fn the_caveat_and_the_stdout_around_a_command_do_not_reach_the_title() {
        let raw = r"<local-command-caveat>Caveat: the messages below were generated by the user.</local-command-caveat>\n<command-name>/theme</command-name>\n<local-command-stdout>Using custom theme</local-command-stdout>";
        assert_eq!(from_prompt(raw).as_deref(), Some("/theme"));
    }

    #[test]
    fn a_system_reminder_is_not_the_prompt_and_is_taken_off() {
        let raw = r"<system-reminder>Codebase instructions follow.</system-reminder>read the grid scanner back to me";
        assert_eq!(from_prompt(raw).as_deref(), Some("read the grid scanner back to me"));
    }

    #[test]
    fn a_pasted_block_reads_as_its_own_contents() {
        let raw = r#"look at <pasted_content id="7a1f">a stack trace</pasted_content id="7a1f"> please"#;
        assert_eq!(from_prompt(raw).as_deref(), Some("look at a stack trace please"));
    }

    #[test]
    fn a_prompt_that_is_nothing_but_envelope_has_no_title_in_it() {
        let raw = r"<local-command-stdout>Using custom theme</local-command-stdout>";
        assert_eq!(from_prompt(raw), None);
        assert_eq!(from_prompt("   "), None);
    }

    #[test]
    fn a_multi_line_prompt_folds_onto_one_line() {
        assert_eq!(from_prompt(r"first line\nsecond   line").as_deref(), Some("first line second line"));
    }

    #[test]
    fn a_tag_the_user_wrote_themselves_survives() {
        assert_eq!(from_prompt("why does <div> render twice").as_deref(), Some("why does <div> render twice"));
    }

    #[test]
    fn a_latch_title_is_unescaped_and_flattened() {
        assert_eq!(from_latch(r"Rebuild\nthe scanner").as_deref(), Some("Rebuild the scanner"));
        assert_eq!(from_latch(""), None);
    }
}
